### ISSUE TITLE
does not handle circular nested objects

### ISSUE THREAD

**Issue by goldenjayr** [arfeo/find-and#1]
`I` found your module in stackoverflow and I thought this one will solve my problem in modifying data in redis cache.

Basically I want to modify a field within an object with a specific id in redis cache using graphql. 

so I have a data like: 

const data: {
               projects: [
                       {
                        name: 'sample',
                        id: 1
                        photos: [
                                  id: 12,
                                  project: {
                                           id: 1
                                           name: 'sample'
                                             }
                                       ]
                                }                           
                            ]
                       }

So i want to modify the name of a project with id 1. 
using the changeProps it should have also changed the project inside photos but it doesnt

**Comment by arfeo** [comment]
Thank you for discovering a bug! Fixed in 1.1.3
